/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarsRouteImport } from './routes/wars'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as VisualizerRouteImport } from './routes/visualizer'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as DevInterviewRouteImport } from './routes/dev-interview'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const WarsRoute = WarsRouteImport.update({
  id: '/wars',
  path: '/wars',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizerRoute = VisualizerRouteImport.update({
  id: '/visualizer',
  path: '/visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const DevInterviewRoute = DevInterviewRouteImport.update({
  id: '/dev-interview',
  path: '/dev-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/dev-interview': typeof DevInterviewRoute
  '/focus': typeof FocusRoute
  '/health': typeof HealthRoute
  '/learning': typeof LearningRoute
  '/mistakes': typeof MistakesRoute
  '/mood': typeof MoodRoute
  '/performance': typeof PerformanceRoute
  '/projects': typeof ProjectsRoute
  '/quiz': typeof QuizRoute
  '/skills': typeof SkillsRoute
  '/teach': typeof TeachRoute
  '/timetable': typeof TimetableRoute
  '/tutor': typeof TutorRoute
  '/vault': typeof VaultRoute
  '/visualizer': typeof VisualizerRoute
  '/voice': typeof VoiceRoute
  '/wars': typeof WarsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/dev-interview': typeof DevInterviewRoute
  '/focus': typeof FocusRoute
  '/health': typeof HealthRoute
  '/learning': typeof LearningRoute
  '/mistakes': typeof MistakesRoute
  '/mood': typeof MoodRoute
  '/performance': typeof PerformanceRoute
  '/projects': typeof ProjectsRoute
  '/quiz': typeof QuizRoute
  '/skills': typeof SkillsRoute
  '/teach': typeof TeachRoute
  '/timetable': typeof TimetableRoute
  '/tutor': typeof TutorRoute
  '/vault': typeof VaultRoute
  '/visualizer': typeof VisualizerRoute
  '/voice': typeof VoiceRoute
  '/wars': typeof WarsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/dev-interview': typeof DevInterviewRoute
  '/focus': typeof FocusRoute
  '/health': typeof HealthRoute
  '/learning': typeof LearningRoute
  '/mistakes': typeof MistakesRoute
  '/mood': typeof MoodRoute
  '/performance': typeof PerformanceRoute
  '/projects': typeof ProjectsRoute
  '/quiz': typeof QuizRoute
  '/skills': typeof SkillsRoute
  '/teach': typeof TeachRoute
  '/timetable': typeof TimetableRoute
  '/tutor': typeof TutorRoute
  '/vault': typeof VaultRoute
  '/visualizer': typeof VisualizerRoute
  '/voice': typeof VoiceRoute
  '/wars': typeof WarsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avatar'
    | '/career'
    | '/dashboard'
    | '/dev-interview'
    | '/focus'
    | '/health'
    | '/learning'
    | '/mistakes'
    | '/mood'
    | '/performance'
    | '/projects'
    | '/quiz'
    | '/skills'
    | '/teach'
    | '/timetable'
    | '/tutor'
    | '/vault'
    | '/visualizer'
    | '/voice'
    | '/wars'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avatar'
    | '/career'
    | '/dashboard'
    | '/dev-interview'
    | '/focus'
    | '/health'
    | '/learning'
    | '/mistakes'
    | '/mood'
    | '/performance'
    | '/projects'
    | '/quiz'
    | '/skills'
    | '/teach'
    | '/timetable'
    | '/tutor'
    | '/vault'
    | '/visualizer'
    | '/voice'
    | '/wars'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/avatar'
    | '/career'
    | '/dashboard'
    | '/dev-interview'
    | '/focus'
    | '/health'
    | '/learning'
    | '/mistakes'
    | '/mood'
    | '/performance'
    | '/projects'
    | '/quiz'
    | '/skills'
    | '/teach'
    | '/timetable'
    | '/tutor'
    | '/vault'
    | '/visualizer'
    | '/voice'
    | '/wars'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AvatarRoute: typeof AvatarRoute
  CareerRoute: typeof CareerRoute
  DashboardRoute: typeof DashboardRoute
  DevInterviewRoute: typeof DevInterviewRoute
  FocusRoute: typeof FocusRoute
  HealthRoute: typeof HealthRoute
  LearningRoute: typeof LearningRoute
  MistakesRoute: typeof MistakesRoute
  MoodRoute: typeof MoodRoute
  PerformanceRoute: typeof PerformanceRoute
  ProjectsRoute: typeof ProjectsRoute
  QuizRoute: typeof QuizRoute
  SkillsRoute: typeof SkillsRoute
  TeachRoute: typeof TeachRoute
  TimetableRoute: typeof TimetableRoute
  TutorRoute: typeof TutorRoute
  VaultRoute: typeof VaultRoute
  VisualizerRoute: typeof VisualizerRoute
  VoiceRoute: typeof VoiceRoute
  WarsRoute: typeof WarsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wars': {
      id: '/wars'
      path: '/wars'
      fullPath: '/wars'
      preLoaderRoute: typeof WarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizer': {
      id: '/visualizer'
      path: '/visualizer'
      fullPath: '/visualizer'
      preLoaderRoute: typeof VisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-interview': {
      id: '/dev-interview'
      path: '/dev-interview'
      fullPath: '/dev-interview'
      preLoaderRoute: typeof DevInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AvatarRoute: AvatarRoute,
  CareerRoute: CareerRoute,
  DashboardRoute: DashboardRoute,
  DevInterviewRoute: DevInterviewRoute,
  FocusRoute: FocusRoute,
  HealthRoute: HealthRoute,
  LearningRoute: LearningRoute,
  MistakesRoute: MistakesRoute,
  MoodRoute: MoodRoute,
  PerformanceRoute: PerformanceRoute,
  ProjectsRoute: ProjectsRoute,
  QuizRoute: QuizRoute,
  SkillsRoute: SkillsRoute,
  TeachRoute: TeachRoute,
  TimetableRoute: TimetableRoute,
  TutorRoute: TutorRoute,
  VaultRoute: VaultRoute,
  VisualizerRoute: VisualizerRoute,
  VoiceRoute: VoiceRoute,
  WarsRoute: WarsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
